# Generated by Django 3.2.6 on 2021-08-07 17:53

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, choices=[('Locked', 'Locked'), ('Unlocked', 'Unlocked')], default='Unlocked', max_length=10, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('bio', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('followers_count', models.IntegerField(default=0, null=True)),
                ('following_count', models.IntegerField(default=0, null=True)),
                ('profile_picture', models.ImageField(upload_to='')),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='User_Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_link', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('github_link', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('linkedin_link', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('instagram_link', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('twitter_link', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Socials',
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='Password_Resets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True)),
                ('is_token_used', models.BooleanField(default=False)),
                ('expired_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Password Resets',
                'ordering': ['user_id'],
            },
        ),
    ]
