# Generated by Django 3.2.6 on 2021-08-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='bio',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='occupation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
