# Generated by Django 3.2.4 on 2021-06-28 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_socials',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='smapp.users'),
        ),
    ]
