# Generated by Django 3.2.5 on 2021-07-12 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='comments_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='likes_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user_socials',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='smapp.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='followers_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='following_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
