# Generated by Django 3.2.5 on 2021-07-29 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='receiver_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='message_receiver', to='accounts.users'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messages',
            name='sender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='message_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
