# Generated by Django 3.2.5 on 2021-07-12 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0002_auto_20210712_0800'),
        ('smapp', '0005_auto_20210703_2158'),
    ]

    operations = [
    ]
